project:
  type: book
  post-render: scripts/copy-redirect.sh

profile:
  default: en
  group:
    - [en, pt]

book:
  title: "Data Not Found"
  date: "April, 2026"
  sidebar:
    collapse-level: 1


file-scope: true

bibliography:
  - bib/references_global.bib
  - bib/bluesky.bib
  - bib/discord.bib
  - bib/kwai.bib
  - bib/meta.bib
  - bib/reddit.bib
  - bib/linkedin.bib
  - bib/tiktok.bib
  - bib/twitter.bib
  - bib/whatsapp.bib
  - bib/x.bib

format:
  html:
    date-format: "MMMM, YYYY"
    theme: cosmo
    css: custom.css
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    code-tools: false
    embed-resources: false

execute:
  freeze: auto
  parallel: true
  echo: false
  warning: false
  message: false

jupyter: python3
